In [1]:
import pandas as pd
filepath = 'C:\Class\미드텀\data\지하철_유무임별_이용현황.xls'
df = pd.read_excel(filepath)
df

          사용월  호선명   역ID      지하철역       유임승차       유임하차     무임승차     무임하차
0     2022-05  1호선   150       서울역  1,190,797  1,163,681  205,902  197,470
1     2022-05  1호선   151        시청    558,803    570,475   85,828   83,940
2     2022-05  1호선   152        종각    863,844    838,956  143,903  132,619
3     2022-05  1호선   153      종로3가    481,950    426,618  311,628  287,827
4     2022-05  1호선   154      종로5가    408,794    416,893  267,599  254,913
...       ...  ...   ...       ...        ...        ...      ...      ...
7368  2023-04  신림선  4407        당곡     92,996     88,941   35,177   34,386
7369  2023-04  신림선  4408        신림     35,458     53,929   15,135   18,071
7370  2023-04  신림선  4409        서원     76,664     62,214   22,909   22,747
7371  2023-04  신림선  4410   서울대벤처타운    208,339    187,189   61,271   61,560
7372  2023-04  신림선  4411  관악산(서울대)     63,684     69,063   35,209   35,595

[7373 rows x 8 columns]

In [2]:
df.head()

       사용월  호선명  역ID  지하철역       유임승차       유임하차     무임승차     무임하차
0  2022-05  1호선  150   서울역  1,190,797  1,163,681  205,902  197,470
1  2022-05  1호선  151    시청    558,803    570,475   85,828   83,940
2  2022-05  1호선  152    종각    863,844    838,956  143,903  132,619
3  2022-05  1호선  153  종로3가    481,950    426,618  311,628  287,827
4  2022-05  1호선  154  종로5가    408,794    416,893  267,599  254,913

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7373 entries, 0 to 7372
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용월     7373 non-null   object
 1   호선명     7373 non-null   object
 2   역ID     7373 non-null   int64
 3   지하철역    7373 non-null   object
 4   유임승차    7373 non-null   object
 5   유임하차    7373 non-null   object
 6   무임승차    7373 non-null   object
 7   무임하차    7373 non-null   object
dtypes: int64(1), object(7)
memory usage: 460.9+ KB

In [4]:
df['유임승차'] = df['유임승차'].str.replace(',', '').astype(int)
df['유임하차'] = df['유임하차'].str.replace(',', '').astype(int)
df['무임승차'] = df['무임승차'].str.replace(',', '').astype(int)
df['무임하차'] = df['무임하차'].str.replace(',', '').astype(int)

In [18]:
df = df[~df['호선명'].str.contains('신림선|우이신설선|경부선|경인선|경원선|경의선|경강선|경춘선|\
                               |중앙선|수원선|수인선|과천선|장항선|일산선|안산선|9호선|\
                               9호선2~3단계|공항철도 1호선|분당선')]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3335 entries, 0 to 7296
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용월     3335 non-null   object
 1   호선명     3335 non-null   object
 2   역ID     3335 non-null   int64
 3   지하철역    3335 non-null   object
 4   유임승차    3335 non-null   int32
 5   유임하차    3335 non-null   int32
 6   무임승차    3335 non-null   int32
 7   무임하차    3335 non-null   int32
 8   무임승차율   3335 non-null   float64
 9   무임하차율   3264 non-null   float64
dtypes: float64(2), int32(4), int64(1), object(3)
memory usage: 234.5+ KB

In [20]:
df['무임승차율']=df['무임승차']/((df['유임승차'])+(df['무임승차']))

In [21]:
df['무임하차율']=df['무임하차']/((df['유임하차'])+(df['무임하차']))

In [22]:
ride=df.groupby(['호선명','지하철역'])[['무임승차율', '무임하차율']].mean()
ride

                 무임승차율     무임하차율
호선명 지하철역
1호선 동대문       0.350045  0.362715
    동묘앞       0.534855  0.523435
    서울역       0.136554  0.134663
    시청        0.132048  0.127293
    신설동       0.295314  0.294555
...                ...       ...
8호선 신흥        0.281799  0.275816
    암사        0.192847  0.215143
    잠실(송파구청)  0.159481  0.132904
    장지        0.160348  0.159867
    천호(풍납토성)  0.192203  0.159878

[284 rows x 2 columns]

In [23]:
ride.sort_values(['무임승차율'],ascending=False).head(50)

                      무임승차율     무임하차율
호선명 지하철역
1호선 제기동            0.542516  0.570689
    동묘앞            0.534855  0.523435
    청량리(서울시립대입구)   0.429560  0.433233
    종로3가           0.389130  0.395657
8호선 모란             0.387958  0.366350
1호선 종로5가           0.368299  0.357359
    동대문            0.350045  0.362715
6호선 월드컵경기장(성산)     0.342199  0.309004
7호선 삼산체육관          0.333333       NaN
2호선 용두(동대문구청)      0.332911  0.348834
4호선 동작(현충원)        0.326789  0.301159
5호선 길동             0.314376  0.309686
3호선 독립문            0.313027  0.303252
5호선 하남시청(덕풍·신장)    0.307381  0.322360
6호선 불광             0.307255  0.261847
1호선 신설동            0.295314  0.294555
2호선 신설동            0.294545  0.314350
6호선 역촌             0.294396  0.248772
3호선 가락시장           0.293507  0.291791
    불광             0.289668  0.295970
8호선 수진             0.286610  0.307643
    신흥             0.281799  0.275816
    가락시장           0.277811  0.255027
4호선 당고개            0.277447  0.303506
6호선 동묘앞            0.275214  0.252822
5호선 명일             0.273684  0.276659
4호선 총신대입구(이수)      0.270956  0.260552
    동대문            0.270677  0.256271
3호선 홍제             0.270216  0.280197
4호선 창동             0.270201  0.264040
5호선 마천             0.266481  0.283640
    굽은다리(강동구민회관앞)  0.265129  0.257703
    방화             0.263814  0.268188
7호선 수락산            0.262167  0.269916
5호선 올림픽공원(한국체대)    0.261302  0.264738
    개롱             0.260947  0.258249
    송정             0.260485  0.268873
4호선 회현(남대문시장)      0.260482  0.250284
5호선 하남검단산          0.259952  0.268355
    강일             0.257281  0.266855
3호선 무악재            0.256849  0.276062
5호선 둔촌동            0.256271  0.257322
    고덕             0.253412  0.253778
4호선 미아(서울사이버대학)    0.252952  0.267044
7호선 장승배기           0.252934  0.263792
2호선 양천구청           0.246420  0.242214
6호선 독바위            0.245613  0.285730
3호선 학여울            0.244891  0.235173
5호선 마장             0.244533  0.252748
6호선 증산(명지대앞)       0.243416  0.248586

In [24]:
ride.sort_values(['무임하차율'],ascending=False).head(50)

                      무임승차율     무임하차율
호선명 지하철역
1호선 제기동            0.542516  0.570689
    동묘앞            0.534855  0.523435
    청량리(서울시립대입구)   0.429560  0.433233
    종로3가           0.389130  0.395657
8호선 모란             0.387958  0.366350
1호선 동대문            0.350045  0.362715
    종로5가           0.368299  0.357359
2호선 용두(동대문구청)      0.332911  0.348834
5호선 하남시청(덕풍·신장)    0.307381  0.322360
2호선 신설동            0.294545  0.314350
6호선 구산             0.225011  0.313529
5호선 길동             0.314376  0.309686
6호선 월드컵경기장(성산)     0.342199  0.309004
8호선 수진             0.286610  0.307643
4호선 당고개            0.277447  0.303506
3호선 독립문            0.313027  0.303252
4호선 동작(현충원)        0.326789  0.301159
3호선 불광             0.289668  0.295970
1호선 신설동            0.295314  0.294555
3호선 가락시장           0.293507  0.291791
6호선 독바위            0.245613  0.285730
5호선 마천             0.266481  0.283640
3호선 홍제             0.270216  0.280197
5호선 명일             0.273684  0.276659
3호선 무악재            0.256849  0.276062
8호선 신흥             0.281799  0.275816
7호선 수락산            0.262167  0.269916
5호선 송정             0.260485  0.268873
    하남검단산          0.259952  0.268355
    방화             0.263814  0.268188
4호선 미아(서울사이버대학)    0.252952  0.267044
5호선 강일             0.257281  0.266855
    올림픽공원(한국체대)    0.261302  0.264738
4호선 창동             0.270201  0.264040
7호선 장승배기           0.252934  0.263792
6호선 불광             0.307255  0.261847
4호선 총신대입구(이수)      0.270956  0.260552
5호선 개롱             0.260947  0.258249
    굽은다리(강동구민회관앞)  0.265129  0.257703
    둔촌동            0.256271  0.257322
4호선 동대문            0.270677  0.256271
8호선 가락시장           0.277811  0.255027
6호선 버티고개           0.216487  0.254638
5호선 고덕             0.253412  0.253778
7호선 장암             0.157074  0.252905
6호선 동묘앞            0.275214  0.252822
5호선 마장             0.244533  0.252748
    개화산            0.240913  0.251199
6호선 새절(신사)         0.233491  0.250653
4호선 회현(남대문시장)      0.260482  0.250284